### ISSUE TITLE
Getting package name and version from package.json

### ISSUE THREAD

**Issue by olivif** [IonicaBizau/node-clp#11]
Potentially a new feature :muscle: , but it would be pretty cool if clp could fetch the package name and version from the package.json directly. It would remove some duplication, as right now there's a high chance you modify one and forget the other :smile:

**Comment by IonicaBizau** [comment]
@olivif Would be a nice feature! :+1: 

I usually do [`require("../package")`](https://github.com/IonicaBizau/git-stats/blob/master/bin/git-stats#L12) but I'm not sure if what you want is possible: how to get the path to the `package.json` of the dependent module having `clp` as dependency?

**Comment by olivif** [comment]
@IonicaBizau hmm, good point, it would be hard for clp to figure it out from within itself. 

The only way I can think of is for the dependent module to initialize clp with the info itself (as it does now) or with something that contains the info and clp knows how to extract it. Off the top of my head, it could be either the `package.json` (path or json itself, and clp gets the fields) or something like `process.env` (which should have `npm_package_version` and name and description).

**Comment by IonicaBizau** [comment]
@olivif I'm almost sure it's possible to get the `package.json` content when the script is executed by `npm` (`npm run some-script` and probably also in the `bin` case).

To get the version you can do `process.env.npm_package_version` (which is the `package.json` version where the script is executed from or `"No version"` otherwise).

However, this is dependent module logic. A wrapper can be built to handle that if that's really needed. :smile:

**Comment by IonicaBizau** [comment]
Passing the path to a `package.json`(-like) file is supported now supported in [`tilda`](https://github.com/IonicaBizau/tilda). :tada: :dizzy: /cc #13 :rocket:
